### ISSUE TITLE
Extracting email settings into the configutation file.

### ISSUE THREAD

**Issue by AlBundyLoves69** [NAUbackup/VmBackup#81] opened 2018-06-15 14:29 UTC
While testing the new version 3.23 I was thinking that it would more comfortable when the email settings

```
MAIL_TO_ADDR = 'your-email@your-domain'
MAIL_FROM_ADDR = 'your-from-address@your-domain'
MAIL_SMTP_SERVER = 'your-mail-server'
```

would be extracted into the configuration file. Currently these settings have to be maintained each time a new version is installed.

Further, when the configuration file would have a setting like `send_email` which controls the email behaviour, this lightens also the update process.

Also, the current SMTP authentication method gets lost each time a new update is installed [function send_email]. To solve this in with a configuration file may become a bit tricky...

PS: On Sunday I will write in the other thread how the test was.

UPS: I see I opened already an issue regarding this #72 . Can you delete this? **SORRY**

**Comment by NAUbackup** [comment] 2018-06-15 16:30
Closed, since a duplicate of #72 .

**Closed by NAUbackup** 2018-06-15 16:30 UTC
